# Generated by Django 5.1.6 on 2025-04-08 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_evento_descripcion'),
        ('eventos', '0004_alter_evento_usuario_alter_notificacion_usuario'),
    ]

    operations = [
    ]
