# Generated by Django 5.1.6 on 2025-03-05 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=150)),
                ('apellidos', models.CharField(max_length=150)),
                ('cedula', models.CharField(max_length=10, unique=True)),
                ('celular', models.CharField(max_length=10)),
            ],
        ),
    ]
