# Generated by Django 5.1.6 on 2025-03-05 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_empleado_contrasena_empleado_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='contrasena',
        ),
    ]
