# Generated by Django 5.1.6 on 2025-03-12 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carpetas', '0001_initial'),
        ('control_procesos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proceso', models.CharField(max_length=200)),
                ('responsable', models.CharField(default='Desconocido', max_length=200)),
                ('calificacion', models.CharField(blank=True, max_length=100, null=True)),
                ('actor', models.CharField(default='Desconocido', max_length=200)),
                ('demandado', models.CharField(default='Desconocido', max_length=200)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('posesion', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_cumplimiento', models.DateField(blank=True, null=True)),
                ('fecha_limite', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('folder_path', models.CharField(blank=True, max_length=255, null=True)),
                ('carpeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procesos', to='carpetas.carpeta')),
            ],
        ),
    ]
