# Generated by Django 5.1.6 on 2025-03-12 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_procesos', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proceso',
            name='folder_path',
        ),
    ]
