# Generated by Django 5.1.6 on 2025-03-13 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_procesos', '0003_remove_proceso_folder_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='proceso',
            name='sorteo',
            field=models.DateField(blank=True, null=True),
        ),
    ]
