# Generated by Django 5.1.6 on 2025-03-14 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_procesos', '0004_proceso_sorteo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_respuesta', models.DateField(blank=True, null=True)),
                ('calificacion', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_cumplimiento', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='control_procesos.proceso')),
            ],
        ),
    ]
