# Generated by Django 5.1.6 on 2025-03-14 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_procesos', '0006_respuesta_carpeta_alter_respuesta_fecha_respuesta'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaPorCobrar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de Factura')),
                ('cobro', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Cobrado')),
                ('saldo', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Saldo')),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='Observación')),
                ('proceso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cuenta_cobrar', to='control_procesos.proceso')),
            ],
            options={
                'verbose_name': 'Cuenta por Cobrar',
                'verbose_name_plural': 'Cuentas por Cobrar',
            },
        ),
    ]
