# Generated by Django 5.1.6 on 2025-03-14 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpetas', '0001_initial'),
        ('control_procesos', '0007_cuentaporcobrar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuentaporcobrar',
            options={},
        ),
        migrations.AddField(
            model_name='cuentaporcobrar',
            name='carpeta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_por_cobrar', to='carpetas.carpeta'),
        ),
        migrations.AlterField(
            model_name='cuentaporcobrar',
            name='cobro',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cuentaporcobrar',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cuentaporcobrar',
            name='observacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cuentaporcobrar',
            name='proceso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_procesos.proceso'),
        ),
        migrations.AlterField(
            model_name='cuentaporcobrar',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
