# Generated by Django 5.1.6 on 2025-03-14 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpetas', '0001_initial'),
        ('control_procesos', '0008_alter_cuentaporcobrar_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentaporcobrar',
            name='carpeta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_por_cobrar', to='carpetas.carpeta'),
        ),
        migrations.AlterField(
            model_name='cuentaporcobrar',
            name='proceso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentaporcobrar', to='control_procesos.proceso'),
        ),
    ]
