# Generated by Django 5.1.6 on 2025-03-14 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_procesos', '0009_alter_cuentaporcobrar_carpeta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentaporcobrar',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cuentaporcobrar',
            name='proceso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_cobrar', to='control_procesos.proceso'),
        ),
    ]
