# Generated by Django 5.1.6 on 2025-03-14 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_procesos', '0010_alter_cuentaporcobrar_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentaporcobrar',
            name='saldo',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
