# Generated by Django 5.1.6 on 2025-03-18 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_procesos', '0012_notificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='CXC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cliente')),
                ('numero_factura', models.CharField(blank=True, max_length=100, null=True, verbose_name='# Factura')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('real', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Real')),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='Observación')),
            ],
        ),
    ]
