# Generated by Django 5.1.6 on 2025-03-18 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpetas', '0001_initial'),
        ('control_procesos', '0013_cxc'),
    ]

    operations = [
        migrations.AddField(
            model_name='cxc',
            name='carpeta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cxcs', to='carpetas.carpeta'),
        ),
        migrations.AlterField(
            model_name='cxc',
            name='cliente',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cxc',
            name='fecha',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cxc',
            name='numero_factura',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cxc',
            name='observacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cxc',
            name='real',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
