# Generated by Django 5.1.6 on 2025-03-19 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpetas', '0001_initial'),
        ('control_procesos', '0014_cxc_carpeta_alter_cxc_cliente_alter_cxc_fecha_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroFirma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perito', models.CharField(max_length=100)),
                ('ruc', models.CharField(max_length=20)),
                ('clave', models.CharField(max_length=100)),
                ('carpeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firmas', to='carpetas.carpeta')),
            ],
        ),
    ]
