# Generated by Django 5.1.6 on 2025-03-21 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpetas', '0001_initial'),
        ('control_procesos', '0015_registrofirma'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compania', models.CharField(blank=True, max_length=100, null=True)),
                ('institucion_financiera', models.CharField(blank=True, max_length=150, null=True)),
                ('numero', models.CharField(blank=True, max_length=50, null=True)),
                ('ruc_ci', models.CharField(blank=True, max_length=20, null=True)),
                ('usuario', models.CharField(blank=True, max_length=50, null=True)),
                ('clave_web', models.CharField(blank=True, max_length=100, null=True)),
                ('clave_cajero', models.CharField(blank=True, max_length=100, null=True)),
                ('clave_trush', models.CharField(blank=True, max_length=100, null=True)),
                ('clave_sut', models.CharField(blank=True, max_length=100, null=True)),
                ('carpeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentasEspeciales', to='carpetas.carpeta')),
            ],
        ),
    ]
