# Generated by Django 5.1.6 on 2025-03-21 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpetas', '0001_initial'),
        ('control_procesos', '0016_registrocuenta'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroPregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.TextField()),
                ('respuesta', models.TextField(blank=True, null=True)),
                ('carpeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntasEspeciales', to='carpetas.carpeta')),
            ],
        ),
    ]
