# Generated by Django 5.1.6 on 2025-03-21 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpetas', '0001_initial'),
        ('control_procesos', '0017_registropregunta'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroClavesSistemas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compania', models.CharField(blank=True, max_length=200, null=True)),
                ('canton', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('clave_mail', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_declaracion', models.DateField(blank=True, null=True)),
                ('declaracion', models.CharField(blank=True, max_length=100, null=True)),
                ('ruc', models.CharField(blank=True, max_length=20, null=True)),
                ('clave_sri', models.CharField(blank=True, max_length=100, null=True)),
                ('clave_super', models.CharField(blank=True, max_length=100, null=True)),
                ('clave_iess', models.CharField(blank=True, max_length=100, null=True)),
                ('perito_judicial', models.CharField(blank=True, max_length=100, null=True)),
                ('carpeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clavesSistemas', to='carpetas.carpeta')),
            ],
        ),
    ]
