# Generated by Django 5.1.6 on 2025-03-22 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_procesos', '0019_registrosistema'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='proceso',
            name='estado',
            field=models.CharField(choices=[('hecho', 'Hecho'), ('pendiente', 'Pendiente'), ('faltan_datos', 'Faltan datos')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsable'),
        ),
    ]
