# Generated by Django 5.1.6 on 2025-03-24 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpetas', '0001_initial'),
        ('control_procesos', '0020_proceso_estado_alter_proceso_responsable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('titular', models.CharField(max_length=100)),
                ('numero_cuenta', models.CharField(max_length=50)),
                ('tipo_cuenta', models.CharField(max_length=50)),
                ('ruc', models.CharField(blank=True, max_length=13, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('carpeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bancos', to='carpetas.carpeta')),
            ],
        ),
    ]
