# Generated by Django 5.1.6 on 2025-03-24 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_procesos', '0021_banco'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banco',
        ),
    ]
