# Generated by Django 5.1.6 on 2025-03-24 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpetas', '0001_initial'),
        ('control_procesos', '0022_delete_banco'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compania', models.CharField(max_length=100)),
                ('institucion_financiera', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=50)),
                ('ruc_ci', models.CharField(max_length=20)),
                ('usuario', models.CharField(max_length=100)),
                ('clave_web', models.CharField(max_length=100)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('carpeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bancos', to='carpetas.carpeta')),
            ],
        ),
    ]
